name: Code analysis and dependency submission

on:
  pull_request:
  workflow_dispatch:
  schedule: ## Kjører kl. 05:00 mandag -> fredag
    - cron: '0 5 * * 1-5'

jobs:
  analyze_code:
    name: Analyze Code
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: navikt/sosialhjelp-ci/.github/workflows/codeql_java.yml@master

  dependency_submission:
    name: Dependency Submission
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubUser: ${{ inputs.githubUser }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Java with'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Run dependency submission from Snapshot
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          gradle-build-module: |-
            :sosialhjelp-common-api
            :sosialhjelp-common-kotlin-utils
            :sosialhjelp-common-selftest
          sub-module-mode: INDIVIDUAL_DEEP
