name: Publish artifacts (snapshot)
on:
  push:
    branches:
      - '*'
      - '*/*' # in case a branch uses this naming pattern
      - '!main'
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Run lint
        run: ./gradlew ktlintCheck
      - name: test and build
        run: ./gradlew -Pversion="1.$(echo $GITHUB_SHA | cut -c1-7)-SNAPSHOT" build
      - name: upload artifact
        run: ./gradlew -Pversion="1.$(echo $GITHUB_SHA | cut -c1-7)-SNAPSHOT" publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}